image: ubuntu:latest

before_script:
  - apt-get update -y && apt-get install sshpass -y

stages:
  - build
  - deploy

build-job:
  image: maven:latest
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn package
  artifacts:
    paths:
      - target/

build image:
  image: docker:19.03.12
  stage: deploy
  services:
    - name: docker:19.03.12-dind
      entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
  variables:
    DOCKER_TLS_CERTDIR: ''
    DOCKER_HOST: "tcp://docker:2375"

  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin 
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - main

deploy-job:
  image: docker:19.03.12
  stage: deploy
  services:
    - name: docker:19.03.12-dind
      entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
  variables:
    DOCKER_TLS_CERTDIR: ''
    DOCKER_HOST: "tcp://docker:2375"
  script:
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan -H 192.168.3.211 >> ~/.ssh/known_hosts
    - ssh -fN -R 2375:localhost:2375 donovan@192.168.3.211
    #- ssh -t donovan@192.168.3.211 'echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin'
    - ssh -t donovan@192.168.3.211 'docker pull $CI_REGISTRY_IMAGE'
    - ssh -t donovan@192.168.3.211 'docker stop test-coverage-backend || true'
    - ssh -t donovan@192.168.3.211 'docker rm test-coverage-backend || true'
    - ssh -t donovan@192.168.3.211 'docker run -d --name test-coverage-backend -p 80:80 $CI_REGISTRY_IMAGE'

    #- echo "Deploying application..."
    #- docker build -t registry.gitlab.com/myusername/myproject . -f Dockerfile
  only:
    - main