variables:
  DOCKER_DRIVER: overlay

before_script:
  - apt-get update -y && apt-get install sshpass -y

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build image:
  image: docker
  stage: build
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE


build-job:
  image: maven:latest
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn package
  artifacts:
    paths:
      - target/*.jar

deploy-job:
  image: docker:latest
  stage: deploy
  services:
        - name: docker:dind
  script:
    - echo "Deploying application..."
    - docker build -t registry.gitlab.com/myusername/myproject . -f Dockerfile
    - echo "Login to gitlab..."
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - echo "Pushing to gitlab..."
    - docker push registry.gitlab.com/myusername/myproject
    - echo "Application successfully deployed"
    #- eval "$(ssh-agent -s)"
    #- echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    #- mkdir -p ~/.ssh
    #- ssh-keyscan -H 192.168.3.211 >> ~/.ssh/known_hosts
    #- scp -r build/* donovan@192.168.3.211:~/testCoverageBackend
  only:
    - main