image: ubuntu:latest

before_script:
  - apt-get update -y && apt-get install sshpass -y

stages:
  - build
  - deploy

build-job:
  image: maven:latest
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn package
  artifacts:
    paths:
      - target/

build image:
  image: docker:19.03.12
  stage: deploy
  services:
    - name: docker:19.03.12-dind
      entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]

  variables:
    DOCKER_TLS_CERTDIR: ''
    DOCKER_HOST: "tcp://docker:2375"

  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin 
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

  only:
    - main

deploy image to server:
  image: docker:19.03.12
  stage: .post
  services:
    - name: docker:19.03.12-dind
      entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
  variables:
    DOCKER_TLS_CERTDIR: ''
    DOCKER_HOST: "tcp://docker:2375"
  dependencies:
    - build image
  script:
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan -H 192.168.3.211 >> ~/.ssh/known_hosts

    - docker save $CI_REGISTRY_IMAGE -o test_coverage_backend.tar
    - scp test_coverage_backend.tar donovan@192.168.3.211:~/
    - ssh donovan@192.168.3.211:~/ 'tar xvf test_coverage_backend.tar && docker load -i test_coverage_backend.tar && docker run -d -p 80:80 capgit.ecs.baylor.edu:5555/capstone-group-4/test-coverage-backend'
  only:
    - main